// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1GLjZWJu-RDva2MPXA8uT0gXnwNAY2cI',
    appId: '1:932274217060:web:cefd7841b215f6c74a7f71',
    messagingSenderId: '932274217060',
    projectId: 'frrrr-3cf2f',
    authDomain: 'frrrr-3cf2f.firebaseapp.com',
    storageBucket: 'frrrr-3cf2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDon0r5IeboNMSKasG74_if6QeUYse84BY',
    appId: '1:932274217060:android:262b325bf02ae7704a7f71',
    messagingSenderId: '932274217060',
    projectId: 'frrrr-3cf2f',
    storageBucket: 'frrrr-3cf2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC83fBefFI9CXgo0jrNrS2ZZmV3zf1aHp4',
    appId: '1:932274217060:ios:f536706ff7af1bc74a7f71',
    messagingSenderId: '932274217060',
    projectId: 'frrrr-3cf2f',
    storageBucket: 'frrrr-3cf2f.appspot.com',
    iosBundleId: 'com.example.frrrrrtime',
  );
}
